name: Run Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django_version:
          - '2.2'
          - '3.2'
          - '4.0'
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
        exclude:
          - django_version: '2.2'
            python-version: '3.10'

          - django_version: '4.0'
            python-version: '3.6'

          - django_version: '4.0'
            python-version: '3.7'

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.django_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -U flake8 coveralls argparse
          pip install -U Django~=${{ matrix.django_version }}

      - name: Lint with flake8
        run: flake8 --ignore=E501,W504 jsignature

      - name: Test Django
        run: |
          python -W error::DeprecationWarning -W error::PendingDeprecationWarning \
            -m coverage run ./runtests.py

      - name: Coverage
        if: ${{ success() }}
        run: |
          coveralls --service=github
